### ISSUE TITLE
File not found error in Google Colab

### ISSUE THREAD

**Issue by edwinwang123** [espnet/interspeech2019-tutorial#6]
nvm issue resolved

**Comment by rohanhsingh** [comment]
are you by any chance referring to this error? -
./path.sh: line 10: /content/espnet/egs/an4/tts1/espnet/egs/an4/tts1/../../../tools/activate_python.sh: No such file or directory

if yes, how did you solve it?

**Comment by edwinwang123** [comment]
No, my error was that I forgot to run a snippet of code that generates the correct file (the XXX_mini files, I think). In the end, I did successfully run all the code.

**Comment by rohanhsingh** [comment]
Alright thanks for the response
